Add database
aperanto-lefko/java-filmorate pull request #4
Opened 2024-11-08 11:31 UTC by aperanto-lefko

Выполнение ТЗ согласно 12 спринту

2024-11-08 20:19 UTC, sergeymamonov requested changes

2024-11-08 20:19 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/dal/storage/user/FriendsDBStorage.java
> +        int id = insert(
Не создавайте переменные, которые потом не будут использоваться.

2024-11-08 20:19 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmDBService.java
> +    private static final LocalDate release = LocalDate.of(1895, 12, 28);
Оформите как константу.

2024-11-08 20:19 UTC, sergeymamonov commented on src/main/resources/schema.sql
> +  name varchar
Размер varchar необходимо ограничивать.

2024-11-08 20:19 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +//@Test
Не оставляйте закомментированных тестов.

2024-11-09 08:57 UTC, aperanto-lefko commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +
done

2024-11-09 08:59 UTC, aperanto-lefko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  /* json для фильма
done

2024-11-09 09:10 UTC, aperanto-lefko commented on src/main/java/ru/yandex/practicum/filmorate/dal/storage/film/FilmGenreDBStorage.java
> +/*
done

2024-11-09 09:13 UTC, aperanto-lefko commented on src/main/java/ru/yandex/practicum/filmorate/dal/storage/film/LikeDBStorage.java
> +        int id = insert(
done

2024-11-09 09:23 UTC, aperanto-lefko commented on src/main/java/ru/yandex/practicum/filmorate/dal/storage/user/FriendsDBStorage.java
> +        int id = insert(
done

2024-11-09 09:28 UTC, aperanto-lefko commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmDBService.java
> +    private static final LocalDate release = LocalDate.of(1895, 12, 28);
done

2024-11-09 09:58 UTC, aperanto-lefko commented on src/main/resources/schema.sql
> +  name varchar
done

2024-11-09 10:01 UTC, aperanto-lefko commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +//@Test
done

2024-11-10 08:56 UTC, aperanto-lefko commented
Код исправлен в соответствии с замечаниями PR. Также добавлены собственные аннотации для авлидации данных, исправлен код в соответствии с этим. Также добавлены тесты аннотаций

2024-11-10 08:56 UTC, aperanto-lefko commented on src/main/java/ru/yandex/practicum/filmorate/dal/storage/film/FilmDbStorage.java
> +            "SELECT f.*" +
done

2024-11-10 09:42 UTC, aperanto-lefko commented
Код исправлен в соответствии с замечаниями PR. Также добавлены собственные аннотации для валидации данных, исправлен код в соответствии с этим. Также добавлены тесты аннотаций и обработка ошибок, связанных с аннотациями.

2024-11-11 20:16 UTC, sergeymamonov approved these changes

2024-11-11 20:16 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/dal/storage/user/FriendsDBStorage.java
> +                    " SELECT u.*" +
Остался запрос со звездочкой. Если вы встречаете какую-то общую ошибку, то найдите фильтр для поиска и поищите по всему проекту.

2024-11-11 20:16 UTC, sergeymamonov commented on src/main/resources/schema.sql
> +    name varchar NOT NULL,
Используйте поиск по проекту, чтобы находить общие моменты в коде. Здесь остался неограниченный varchar.

2024-11-11 20:43 UTC, aperanto-lefko commented on src/main/resources/schema.sql
> +    name varchar NOT NULL,
done

2024-11-13 20:43 UTC, merged